### YamlMime:QSharpType
uid: microsoft.quantum.chemistry.jordanwigner.preparesparsemulticonfigurationalstate
name: PrepareSparseMultiConfigurationalState
type: operation
namespace: Microsoft.Quantum.Chemistry.JordanWigner
summary: Preparação de estado de várias configurações esparsas do estado de avaliação adicionando excitations ao estado de avaliação inicial.
syntax: 'operation PrepareSparseMultiConfigurationalState (initialStatePreparation : (Qubit[] => Unit), excitations : Microsoft.Quantum.Chemistry.JordanWigner.JordanWignerInputState[], qubits : Qubit[]) : Unit'
input:
  content: '(initialStatePreparation : (Qubit[] => Unit), excitations : Microsoft.Quantum.Chemistry.JordanWigner.JordanWignerInputState[], qubits : Qubit[])'
  types:
  - name: initialStatePreparation
    summary: Unitário para preparar o estado de avaliação inicial.
    isOperation: true
    input:
      types:
      - isArray: true
        isPrimitive: true
        uid: Qubit
    output:
      types:
      - isPrimitive: true
        uid: Unit
  - name: excitations
    summary: Excitations do estado de avaliação inicial representado pela amplitude do Excitation e os índices qubit nos quais o Excitation atua.
    isArray: true
    uid: microsoft.quantum.chemistry.jordanwigner.jordanwignerinputstate
  - name: qubits
    summary: Qubits Hamiltonian.
    isArray: true
    isPrimitive: true
    uid: Qubit
output:
  content: Unit
  types:
  - isPrimitive: true
    uid: Unit
metadata:
  ms.openlocfilehash: c97f5e7ec8a4cc26b4fb173414526363db424293
  ms.sourcegitcommit: edcf15044d7bdf4f8b21fb8f6af4bde475eb13a0
  ms.translationtype: MT
  ms.contentlocale: pt-BR
  ms.lasthandoff: 11/05/2019
  ms.locfileid: "73231802"
