### YamlMime:QSharpNamespace
functions: []
name: Microsoft.Quantum.Environment
newtypes: []
operations:
- summary: Retorna o número de qubits disponíveis no momento para o empréstimo.
  uid: Microsoft.Quantum.Environment.GetQubitsAvailableToBorrow
- summary: Retorna o número de qubits disponíveis no momento para uso.
  uid: Microsoft.Quantum.Environment.GetQubitsAvailableToUse
summary: Essas funções fornecem informações sobre o ambiente no qual a computação Quantum está ocorrendo.
uid: Microsoft.Quantum.Environment
metadata:
  ms.openlocfilehash: 87e1659f8ecdd6df99271f7552f683ffed85b151
  ms.sourcegitcommit: a87c1aa8e7453360025e47ba614f25b02ea84ec3
  ms.translationtype: MT
  ms.contentlocale: pt-BR
  ms.lasthandoff: 11/26/2020
  ms.locfileid: "96201437"
