### YamlMime:QSharpType
uid: microsoft.quantum.environment.getqubitsavailabletouse
name: GetQubitsAvailableToUse
type: operation
namespace: Microsoft.Quantum.Environment
summary: Retorna o número de qubits disponíveis no momento para uso.
syntax: 'operation GetQubitsAvailableToUse () : Int'
input:
  content: ()
  types: []
output:
  content: Int
  types:
  - summary: >-
      O número de qubits que podem ser alocados em uma instrução `using`.

      Se o computador de destino que está sendo usado não fornecer essas informações, `-1` será retornado.
    isPrimitive: true
    uid: Int
seeAlso:
- getqubitsavailabletoborrow
metadata:
  ms.openlocfilehash: 1cb1331aa26ec9755a9e379336f46387b61bb0ae
  ms.sourcegitcommit: edcf15044d7bdf4f8b21fb8f6af4bde475eb13a0
  ms.translationtype: MT
  ms.contentlocale: pt-BR
  ms.lasthandoff: 11/05/2019
  ms.locfileid: "73230459"
