### YamlMime:QSharpNamespace
uid: microsoft.quantum.environment
name: Microsoft.Quantum.Environment
summary: " # <a name=\"summary\"></a>Resumo\n Essas funções fornecem informações sobre o ambiente no qual a computação Quantum está ocorrendo."
operations:
- uid: microsoft.quantum.environment.getqubitsavailabletoborrow
  summary: >-
    Retorna o número de qubits disponíveis no momento para o empréstimo.

    Isso inclui qubits não utilizados; ou seja, isso inclui o qubits retornado por `GetQubitsAvailableToUse` .
- uid: microsoft.quantum.environment.getqubitsavailabletouse
  summary: Retorna o número de qubits disponíveis no momento para uso.
metadata:
  ms.openlocfilehash: 7f597d8f429089b0ebf2c22cef1d1b98ea270402
  ms.sourcegitcommit: d6ac6f4345be0dd68f1bcd944f44b08e7a3cf346
  ms.translationtype: MT
  ms.contentlocale: pt-BR
  ms.lasthandoff: 09/02/2020
  ms.locfileid: "89341149"
