### YamlMime:QSharpNamespace
functions: []
name: Microsoft.Quantum.Environment
newtypes: []
operations:
- summary: Retorna o número de qubits disponíveis no momento para o empréstimo. Isso inclui qubits não utilizados; ou seja, isso inclui o qubits retornado por `GetQubitsAvailableToUse` .
  uid: Microsoft.Quantum.Environment.GetQubitsAvailableToBorrow
- summary: Retorna o número de qubits disponíveis no momento para uso.
  uid: Microsoft.Quantum.Environment.GetQubitsAvailableToUse
summary: Essas funções fornecem informações sobre o ambiente no qual a computação Quantum está ocorrendo.
uid: Microsoft.Quantum.Environment
metadata:
  ms.openlocfilehash: 04a3ffe56be7da2c9adc13e2b27fe9ce0f982c44
  ms.sourcegitcommit: 29e0d88a30e4166fa580132124b0eb57e1f0e986
  ms.translationtype: MT
  ms.contentlocale: pt-BR
  ms.lasthandoff: 10/27/2020
  ms.locfileid: "92693581"
